language: c

env:
  matrix:
    - LUA=lua5.1 LIBLUA=liblua5.1-dev     LUA_INCDIR=/usr/include/lua5.1     LUA_LIB=lua5.1
    - LUA=lua5.2 LIBLUA=liblua5.2-dev     LUA_INCDIR=/usr/include/lua5.2     LUA_LIB=lua5.2
    - LUA=luajit LIBLUA=libluajit-5.1-dev LUA_INCDIR=/usr/include/luajit-2.0 LUA_LIB=luajit-5.1

branches:
  only:
    - master

install:
    - sudo apt-get install $LUA -y
    - sudo apt-get install $LIBLUA -y
    - sudo apt-get install luarocks -y
    - sudo luarocks install luchia

script:
    - $LUA os.execute("date");
